//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.EPiServerNamespaceMigration
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EPiServerEntities : DbContext
    {
        public EPiServerEntities()
            : base("name=EPiServerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBigTable> tblBigTables { get; set; }
        public virtual DbSet<tblBigTableReference> tblBigTableReferences { get; set; }
        public virtual DbSet<tblBigTableStoreInfo> tblBigTableStoreInfoes { get; set; }
        public virtual DbSet<tblPageDefinitionType> tblPageDefinitionTypes { get; set; }
        public virtual DbSet<tblPlugIn> tblPlugIns { get; set; }
    }
}
