//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.EPiServerNamespaceMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBigTableReference
    {
        public long pkId { get; set; }
        public int Type { get; set; }
        public string PropertyName { get; set; }
        public string CollectionType { get; set; }
        public string ElementType { get; set; }
        public string ElementStoreName { get; set; }
        public bool IsKey { get; set; }
        public int Index { get; set; }
        public Nullable<bool> BooleanValue { get; set; }
        public Nullable<int> IntegerValue { get; set; }
        public Nullable<long> LongValue { get; set; }
        public Nullable<System.DateTime> DateTimeValue { get; set; }
        public Nullable<System.Guid> GuidValue { get; set; }
        public Nullable<double> FloatValue { get; set; }
        public string StringValue { get; set; }
        public byte[] BinaryValue { get; set; }
        public Nullable<long> RefIdValue { get; set; }
    }
}
