//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.EPiServerNamespaceMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBigTableStoreInfo
    {
        public string StoreName { get; set; }
        public string PropertyName { get; set; }
        public string PropertyMapType { get; set; }
        public int PropertyIndex { get; set; }
        public string PropertyType { get; set; }
        public bool Active { get; set; }
        public int Version { get; set; }
        public string ColumnName { get; set; }
        public Nullable<int> ColumnRowIndex { get; set; }
        public string TableName { get; set; }
    }
}
