//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.EPiServerNamespaceMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBigTable
    {
        public long pkId { get; set; }
        public int Row { get; set; }
        public string StoreName { get; set; }
        public string ItemType { get; set; }
        public Nullable<bool> Boolean01 { get; set; }
        public Nullable<bool> Boolean02 { get; set; }
        public Nullable<bool> Boolean03 { get; set; }
        public Nullable<bool> Boolean04 { get; set; }
        public Nullable<bool> Boolean05 { get; set; }
        public Nullable<int> Integer01 { get; set; }
        public Nullable<int> Integer02 { get; set; }
        public Nullable<int> Integer03 { get; set; }
        public Nullable<int> Integer04 { get; set; }
        public Nullable<int> Integer05 { get; set; }
        public Nullable<int> Integer06 { get; set; }
        public Nullable<int> Integer07 { get; set; }
        public Nullable<int> Integer08 { get; set; }
        public Nullable<int> Integer09 { get; set; }
        public Nullable<int> Integer10 { get; set; }
        public Nullable<long> Long01 { get; set; }
        public Nullable<long> Long02 { get; set; }
        public Nullable<long> Long03 { get; set; }
        public Nullable<long> Long04 { get; set; }
        public Nullable<long> Long05 { get; set; }
        public Nullable<System.DateTime> DateTime01 { get; set; }
        public Nullable<System.DateTime> DateTime02 { get; set; }
        public Nullable<System.DateTime> DateTime03 { get; set; }
        public Nullable<System.DateTime> DateTime04 { get; set; }
        public Nullable<System.DateTime> DateTime05 { get; set; }
        public Nullable<System.Guid> Guid01 { get; set; }
        public Nullable<System.Guid> Guid02 { get; set; }
        public Nullable<System.Guid> Guid03 { get; set; }
        public Nullable<double> Float01 { get; set; }
        public Nullable<double> Float02 { get; set; }
        public Nullable<double> Float03 { get; set; }
        public Nullable<double> Float04 { get; set; }
        public Nullable<double> Float05 { get; set; }
        public Nullable<double> Float06 { get; set; }
        public Nullable<double> Float07 { get; set; }
        public Nullable<decimal> Decimal01 { get; set; }
        public Nullable<decimal> Decimal02 { get; set; }
        public string String01 { get; set; }
        public string String02 { get; set; }
        public string String03 { get; set; }
        public string String04 { get; set; }
        public string String05 { get; set; }
        public string String06 { get; set; }
        public string String07 { get; set; }
        public string String08 { get; set; }
        public string String09 { get; set; }
        public string String10 { get; set; }
        public byte[] Binary01 { get; set; }
        public byte[] Binary02 { get; set; }
        public byte[] Binary03 { get; set; }
        public byte[] Binary04 { get; set; }
        public byte[] Binary05 { get; set; }
        public Nullable<bool> Indexed_Boolean01 { get; set; }
        public Nullable<int> Indexed_Integer01 { get; set; }
        public Nullable<int> Indexed_Integer02 { get; set; }
        public Nullable<int> Indexed_Integer03 { get; set; }
        public Nullable<long> Indexed_Long01 { get; set; }
        public Nullable<long> Indexed_Long02 { get; set; }
        public Nullable<System.DateTime> Indexed_DateTime01 { get; set; }
        public Nullable<System.Guid> Indexed_Guid01 { get; set; }
        public Nullable<double> Indexed_Float01 { get; set; }
        public Nullable<double> Indexed_Float02 { get; set; }
        public Nullable<double> Indexed_Float03 { get; set; }
        public Nullable<decimal> Indexed_Decimal01 { get; set; }
        public string Indexed_String01 { get; set; }
        public string Indexed_String02 { get; set; }
        public string Indexed_String03 { get; set; }
        public byte[] Indexed_Binary01 { get; set; }
    }
}
