//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.EPiServerNamespaceMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPageDefinitionType
    {
        public int pkID { get; set; }
        public int Property { get; set; }
        public string Name { get; set; }
        public string TypeName { get; set; }
        public string AssemblyName { get; set; }
    }
}
