//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LS.EPiServerNamespaceMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlugIn
    {
        public int pkID { get; set; }
        public string AssemblyName { get; set; }
        public string TypeName { get; set; }
        public string Settings { get; set; }
        public System.DateTime Saved { get; set; }
        public System.DateTime Created { get; set; }
        public bool Enabled { get; set; }
    }
}
